services:
  - type: web
    name: SOLISS-trill
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: SOLISS-trill-db
          property: connectionString
      - key: PAYLOAD_SECRET
        generateValue: true
      - key: NEXT_PUBLIC_SERVER_URL
        sync: false
      - key: NODE_ENV
        value: production

databases:
  - name: SOLISS-trill-db
    plan: free
    databaseName: SOLISS
    user: SOLISS
